version: "3"

services:
  docusaurus:
    image: node:8-alpine
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./docs:/app/docs
      - ./website:/app/website
    working_dir: /app/website
    command: 'yarn start'
